# Don't print a new line at the start of the prompt
add_newline = true

format = """$directory $git_branch $git_status
↳ """

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[git_branch]
symbol = " "
format = "[$symbol$branch]($style) ❯"
style = "white bold"

[username]
style_user = "blue bold"
style_root = "#997744 bold"
format = "[$user]($style) "
disabled = false
show_always = true
