alias ..="cd .."
alias cac="~/go/src/bitbucket.org/atlassian/compliance-as-code"
alias cat=bat
alias cls=clear
alias dev="cd ~/workspace"
alias dockerrm='docker stop $(docker ps -aq)'
alias dockerstop='docker stop $(docker ps -aq)'
alias fenv='env | fzf'
alias gb="git branch | fzf-tmux -d 15"
alias gg="git grep"
alias gp="git pull"
alias initnvm=". /usr/local/opt/nvm/nvm.sh"
alias initpyenv='init_pyenv'
alias initruby='eval "$(rbenv init -)"'
alias lg=lazygit
alias nvim="~/nvim/bin/nvim"
alias vi=nvim
alias vim=nvim
